quarkus.native.enabled=false

aws.region=${AWS_REGION:us-east-1}
aws.account-id=${AWS_ACCOUNT_ID:000000000000}

sqs.region=${aws.region}
sqs.queue.name=${SQS_QUEUE_NAME}
sqs.access.key=${AWS_ACCESS_KEY_ID:test}
sqs.secret.key=${AWS_SECRET_ACCESS_KEY:test}
sqs.endpoint.override=${SQS_ENDPOINT_OVERRIDE:}

dynamodb.region=${aws.region}
dynamodb.table.name=${DYNAMODB_TABLE_NAME:events}
dynamodb.table.query.span.s=${DYNAMODB_QUERY_SPAN_S:3600}
dynamodb.table.query.limit=${DYNAMODB_QUERY_LIMIT:100}
dynamodb.index.order-id=order_id_index
dynamodb.index.status-created-at=status_created_at_index
dynamodb.access.key=${AWS_ACCESS_KEY_ID:test}
dynamodb.secret.key=${AWS_SECRET_ACCESS_KEY:test}
dynamodb.endpoint.override=${DYNAMODB_ENDPOINT_OVERRIDE:}

aws.eventbridge.bus-name=${EVENTBRIDGE_BUS_NAME:default}
aws.eventbridge.endpoint.override=${EVENTBRIDGE_ENDPOINT_OVERRIDE:}
aws.eventbridge.bus-arn=${EVENTBRIDGE_BUS_ARN:arn:aws:events:us-east-1:000000000000:event-bus/default-dev}

aws.sqs.queue-name=${SQS_QUEUE_NAME}
aws.sqs.consumer.amount=${SQS_CONSUMER_AMOUNT:5}
aws.sqs.consumer.max-message-per-poll=${SQS_MAX_MESSAGE_PER_POLL:10}
aws.sqs.poll.s=${SQS_POLL_SECONDS:20}

retry.period-ms=${RETRY_PERIOD_MS:300000}
retry.max-attempts=${RETRY_MAX_ATTEMPTS:3}

quarkus.log.level=${LOG_LEVEL:INFO}
quarkus.log.category."by.losik".level=${LOG_LEVEL_BY_LOSIK:DEBUG}

camel.component.aws2-sqs.accessKey=${AWS_ACCESS_KEY_ID:test}
camel.component.aws2-sqs.secretKey=${AWS_SECRET_ACCESS_KEY:test}
camel.component.aws2-sqs.region=${aws.region}
camel.component.aws2-sqs.overrideEndpoint=true
camel.component.aws2-sqs.uriEndpointOverride=${SQS_ENDPOINT_OVERRIDE:}

camel.component.aws2-eventbridge.accessKey=${AWS_ACCESS_KEY_ID:test}
camel.component.aws2-eventbridge.secretKey=${AWS_SECRET_ACCESS_KEY:test}
camel.component.aws2-eventbridge.region=${aws.region}
camel.component.aws2-eventbridge.overrideEndpoint=true
camel.component.aws2-eventbridge.uriEndpointOverride=${EVENTBRIDGE_ENDPOINT_OVERRIDE:}

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.export.prometheus.path=/metrics

quarkus.test.integration-test.enabled=false
quarkus.test.continuous-testing.enabled=false
quarkus.launch.test.enabled=false